export const countryOptions = [
  { value: "", label: "Select country" },
  { value: "Aruba", label: "Aruba" },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Angola", label: "Angola" },
  { value: "Anguilla", label: "Anguilla" },
  { value: "Åland Islands", label: "Åland Islands" },
  { value: "Albania", label: "Albania" },
  { value: "Andorra", label: "Andorra" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "Argentina", label: "Argentina" },
  { value: "Armenia", label: "Armenia" },
  { value: "American Samoa", label: "American Samoa" },
  { value: "Antarctica", label: "Antarctica" },
  { value: "French Southern Territories", label: "French Southern Territories" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { value: "Australia", label: "Australia" },
  { value: "Austria", label: "Austria" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Burundi", label: "Burundi" },
  { value: "Belgium", label: "Belgium" },
  { value: "Benin", label: "Benin" },
  { value: "Bonaire, Sint Eustatius and Saba", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { value: "Saint Barthélemy", label: "Saint Barthélemy" },
  { value: "Belarus", label: "Belarus" },
  { value: "Belize", label: "Belize" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Bolivia, Plurinational State of", label: "Bolivia, Plurinational State of" },
  { value: "Brazil", label: "Brazil" },
  { value: "Barbados", label: "Barbados" },
  { value: "Brunei Darussalam", label: "Brunei Darussalam" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bouvet Island", label: "Bouvet Island" },
  { value: "Botswana", label: "Botswana" },
  { value: "Central African Republic", label: "Central African Republic" },
  { value: "Canada", label: "Canada" },
  { value: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Chile", label: "Chile" },
  { value: "China", label: "China" },
  { value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Congo, The Democratic Republic of the", label: "Congo, The Democratic Republic of the" },
  { value: "Congo", label: "Congo" },
  { value: "Cook Islands", label: "Cook Islands" },
  { value: "Colombia", label: "Colombia" },
  { value: "Comoros", label: "Comoros" },
  { value: "Cabo Verde", label: "Cabo Verde" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cuba", label: "Cuba" },
  { value: "Curaçao", label: "Curaçao" },
  { value: "Christmas Island", label: "Christmas Island" },
  { value: "Cayman Islands", label: "Cayman Islands" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Czechia", label: "Czechia" },
  { value: "Germany", label: "Germany" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Dominica", label: "Dominica" },
  { value: "Denmark", label: "Denmark" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  { value: "Algeria", label: "Algeria" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Egypt", label: "Egypt" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Western Sahara", label: "Western Sahara" },
  { value: "Spain", label: "Spain" },
  { value: "Estonia", label: "Estonia" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Finland", label: "Finland" },
  { value: "Fiji", label: "Fiji" },
  { value: "Falkland Islands (Malvinas)", label: "Falkland Islands (Malvinas)" },
  { value: "France", label: "France" },
  { value: "Faroe Islands", label: "Faroe Islands" },
  { value: "Micronesia, Federated States of", label: "Micronesia, Federated States of" },
  { value: "Gabon", label: "Gabon" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "Georgia", label: "Georgia" },
  { value: "Guernsey", label: "Guernsey" },
  { value: "Ghana", label: "Ghana" },
  { value: "Gibraltar", label: "Gibraltar" },
  { value: "Guinea", label: "Guinea" },
  { value: "Guadeloupe", label: "Guadeloupe" },
  { value: "Gambia", label: "Gambia" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { value: "Greece", label: "Greece" },
  { value: "Grenada", label: "Grenada" },
  { value: "Greenland", label: "Greenland" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "French Guiana", label: "French Guiana" },
  { value: "Guam", label: "Guam" },
  { value: "Guyana", label: "Guyana" },
  { value: "Hong Kong", label: "Hong Kong" },
  { value: "Heard Island and McDonald Islands", label: "Heard Island and McDonald Islands" },
  { value: "Honduras", label: "Honduras" },
  { value: "Croatia", label: "Croatia" },
  { value: "Haiti", label: "Haiti" },
  { value: "Hungary", label: "Hungary" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Isle of Man", label: "Isle of Man" },
  { value: "India", label: "India" },
  { value: "British Indian Ocean Territory", label: "British Indian Ocean Territory" },
  { value: "Ireland", label: "Ireland" },
  { value: "Iran, Islamic Republic of", label: "Iran, Islamic Republic of" },
  { value: "Iraq", label: "Iraq" },
  { value: "Iceland", label: "Iceland" },
  { value: "Israel", label: "Israel" },
  { value: "Italy", label: "Italy" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Jersey", label: "Jersey" },
  { value: "Jordan", label: "Jordan" },
  { value: "Japan", label: "Japan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Kenya", label: "Kenya" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  { value: "Korea, Republic of", label: "Korea, Republic of" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Lao People's Democratic Republic", label: "Lao People's Democratic Republic" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Liberia", label: "Liberia" },
  { value: "Libya", label: "Libya" },
  { value: "Saint Lucia", label: "Saint Lucia" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Latvia", label: "Latvia" },
  { value: "Macao", label: "Macao" },
  { value: "Saint Martin (French part)", label: "Saint Martin (French part)" },
  { value: "Morocco", label: "Morocco" },
  { value: "Monaco", label: "Monaco" },
  { value: "Moldova, Republic of", label: "Moldova, Republic of" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Maldives", label: "Maldives" },
  { value: "Mexico", label: "Mexico" },
  { value: "Marshall Islands", label: "Marshall Islands" },
  { value: "North Macedonia", label: "North Macedonia" },
  { value: "Mali", label: "Mali" },
  { value: "Malta", label: "Malta" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Northern Mariana Islands", label: "Northern Mariana Islands" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Mauritania", label: "Mauritania" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Martinique", label: "Martinique" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Malawi", label: "Malawi" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Mayotte", label: "Mayotte" },
  { value: "Namibia", label: "Namibia" },
  { value: "New Caledonia", label: "New Caledonia" },
  { value: "Niger", label: "Niger" },
  { value: "Norfolk Island", label: "Norfolk Island" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Niue", label: "Niue" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Norway", label: "Norway" },
  { value: "Nepal", label: "Nepal" },
  { value: "Nauru", label: "Nauru" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Oman", label: "Oman" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Panama", label: "Panama" },
  { value: "Pitcairn", label: "Pitcairn" },
  { value: "Peru", label: "Peru" },
  { value: "Philippines", label: "Philippines" },
  { value: "Palau", label: "Palau" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Poland", label: "Poland" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "Korea, Democratic People's Republic of", label: "Korea, Democratic People's Republic of" },
  { value: "Portugal", label: "Portugal" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Palestine, State of", label: "Palestine, State of" },
  { value: "French Polynesia", label: "French Polynesia" },
  { value: "Qatar", label: "Qatar" },
  { value: "Réunion", label: "Réunion" },
  { value: "Romania", label: "Romania" },
  { value: "Russian Federation", label: "Russian Federation" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Sudan", label: "Sudan" },
  { value: "Senegal", label: "Senegal" },
  { value: "Singapore", label: "Singapore" },
  { value: "South Georgia and the South Sandwich Islands", label: "South Georgia and the South Sandwich Islands" },
  { value: "Saint Helena, Ascension and Tristan da Cunha", label: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen" },
  { value: "Solomon Islands", label: "Solomon Islands" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "San Marino", label: "San Marino" },
  { value: "Somalia", label: "Somalia" },
  { value: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon" },
  { value: "Serbia", label: "Serbia" },
  { value: "South Sudan", label: "South Sudan" },
  { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
  { value: "Suriname", label: "Suriname" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "Sweden", label: "Sweden" },
  { value: "Eswatini", label: "Eswatini" },
  { value: "Sint Maarten (Dutch part)", label: "Sint Maarten (Dutch part)" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "Syrian Arab Republic", label: "Syrian Arab Republic" },
  { value: "Turks and Caicos Islands", label: "Turks and Caicos Islands" },
  { value: "Chad", label: "Chad" },
  { value: "Togo", label: "Togo" },
  { value: "Thailand", label: "Thailand" },
  { value: "Tajikistan", label: "Tajikistan" },
  { value: "Tokelau", label: "Tokelau" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Timor-Leste", label: "Timor-Leste" },
  { value: "Tonga", label: "Tonga" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Türkiye", label: "Türkiye" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Taiwan, Province of China", label: "Taiwan, Province of China" },
  { value: "Tanzania, United Republic of", label: "Tanzania, United Republic of" },
  { value: "Uganda", label: "Uganda" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "United States Minor Outlying Islands", label: "United States Minor Outlying Islands" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "United States", label: "United States" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Holy See (Vatican City State)", label: "Holy See (Vatican City State)" },
  { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
  { value: "Venezuela, Bolivarian Republic of", label: "Venezuela, Bolivarian Republic of" },
  { value: "Virgin Islands, British", label: "Virgin Islands, British" },
  { value: "Virgin Islands, U.S.", label: "Virgin Islands, U.S." },
  { value: "Viet Nam", label: "Viet Nam" },
  { value: "Vanuatu", label: "Vanuatu" },
  { value: "Wallis and Futuna", label: "Wallis and Futuna" },
  { value: "Samoa", label: "Samoa" },
  { value: "Yemen", label: "Yemen" },
  { value: "South Africa", label: "South Africa" },
  { value: "Zambia", label: "Zambia" },
  { value: "Zimbabwe", label: "Zimbabwe" },
];

export const languageProficiencyOptions = [
  { value: "", label: "Select proficiency" },
  { value: "Beginner", label: "Beginner" },
  { value: "Intermediate", label: "Intermediate" },
  { value: "Advanced", label: "Advanced" },
  { value: "Native", label: "Native" },
  { value: "Fluent", label: "Fluent" },
];

export const degreeOptions = [
  { value: "", label: "Select degree" },
  { value: "Bachelor's", label: "Bachelor's" },
  { value: "Master's", label: "Master's" },
  { value: "PhD", label: "PhD" },
  { value: "MD", label: "MD" },
  { value: "JD", label: "JD" },
  { value: "MBA", label: "MBA" },
  { value: "Associate", label: "Associate" },
  { value: "Certificate", label: "Certificate" },
  { value: "Diploma", label: "Diploma" },
];

export const stateOptions = [
  { value: "", label: "Select state" },
  { value: "Alabama", label: "Alabama" },
  { value: "Alaska", label: "Alaska" },
  { value: "Arizona", label: "Arizona" },
  { value: "Arkansas", label: "Arkansas" },
  { value: "California", label: "California" },
  { value: "Colorado", label: "Colorado" },
  { value: "Connecticut", label: "Connecticut" },
  { value: "Delaware", label: "Delaware" },
  { value: "Florida", label: "Florida" },
  { value: "Georgia", label: "Georgia" },
  { value: "Hawaii", label: "Hawaii" },
  { value: "Idaho", label: "Idaho" },
  { value: "Illinois", label: "Illinois" },
  { value: "Indiana", label: "Indiana" },
  { value: "Iowa", label: "Iowa" },
  { value: "Kansas", label: "Kansas" },
  { value: "Kentucky", label: "Kentucky" },
  { value: "Louisiana", label: "Louisiana" },
  { value: "Maine", label: "Maine" },
  { value: "Maryland", label: "Maryland" },
  { value: "Massachusetts", label: "Massachusetts" },
  { value: "Michigan", label: "Michigan" },
  { value: "Minnesota", label: "Minnesota" },
  { value: "Mississippi", label: "Mississippi" },
  { value: "Missouri", label: "Missouri" },
  { value: "Montana", label: "Montana" },
  { value: "Nebraska", label: "Nebraska" },
  { value: "Nevada", label: "Nevada" },
  { value: "New Hampshire", label: "New Hampshire" },
  { value: "New Jersey", label: "New Jersey" },
  { value: "New Mexico", label: "New Mexico" },
  { value: "New York", label: "New York" },
  { value: "North Carolina", label: "North Carolina" },
  { value: "North Dakota", label: "North Dakota" },
  { value: "Ohio", label: "Ohio" },
  { value: "Oklahoma", label: "Oklahoma" },
  { value: "Oregon", label: "Oregon" },
  { value: "Pennsylvania", label: "Pennsylvania" },
  { value: "Rhode Island", label: "Rhode Island" },
  { value: "South Carolina", label: "South Carolina" },
  { value: "South Dakota", label: "South Dakota" },
  { value: "Tennessee", label: "Tennessee" },
  { value: "Texas", label: "Texas" },
  { value: "Utah", label: "Utah" },
  { value: "Vermont", label: "Vermont" },
  { value: "Virginia", label: "Virginia" },
  { value: "Washington", label: "Washington" },
  { value: "West Virginia", label: "West Virginia" },
  { value: "Wisconsin", label: "Wisconsin" },
  { value: "Wyoming", label: "Wyoming" },
];

export const monthOptions = [
  { value: "", label: "Select month" },
  { value: "January", label: "January" },
  { value: "February", label: "February" },
  { value: "March", label: "March" },
  { value: "April", label: "April" },
  { value: "May", label: "May" },
  { value: "June", label: "June" },
  { value: "July", label: "July" },
  { value: "August", label: "August" },
  { value: "September", label: "September" },
  { value: "October", label: "October" },
  { value: "November", label: "November" },
  { value: "December", label: "December" },
];

// Generate year options
const currentYear = new Date().getFullYear();
export const yearOptions = [
  { value: "", label: "Select year" },
  ...Array.from({ length: 50 }, (_, i) => {
    const year = currentYear - i;
    return { value: year.toString(), label: year.toString() };
  }),
];

export const namePrefixOptions = [
  { value: "Dr.", label: "Dr." },
  { value: "Mr.", label: "Mr." },
  { value: "Ms.", label: "Ms." },
  { value: "Mrs.", label: "Mrs." },
  { value: "Prof.", label: "Prof." },
];

export const flourishSiteOptions = [
  { value: "", label: "Select site name" },
  {
    value: "Flourish Research – North Miami",
    label: "Flourish Research – North Miami",
  },
  { value: "Flourish Research", label: "Flourish Research" },
  {
    value: "Flourish Research – Boca Raton",
    label: "Flourish Research – Boca Raton",
  },
];

export const membershipStatusOptions = [
  { value: "", label: "Select status" },
  { value: "Active", label: "Active" },
  { value: "Inactive", label: "Inactive" },
  { value: "Pending", label: "Pending" },
  { value: "Expired", label: "Expired" },
];

export const experienceRangeOptions = [
  { value: "", label: "Enter text" },
  { value: "1-5", label: "1-5" },
  { value: "6-10", label: "6-10" },
  { value: "11-20", label: "11-20" },
  { value: "21-50", label: "21-50" },
  { value: "50+", label: "50+" },
];

export const contextOptions = [
  { value: "", label: "Enter text" },
  { value: "Clinical Practice", label: "Clinical Practice" },
  { value: "Research", label: "Research" },
  { value: "Educational", label: "Educational" },
  { value: "Assessment", label: "Assessment" },
  { value: "Therapy", label: "Therapy" },
  { value: "Other", label: "Other" },
];

export const rolePositionOptions = [
  { value: "", label: "Select role/position" },
  { value: "Principal Investigator", label: "Principal Investigator" },
  { value: "Co-Investigator", label: "Co-Investigator" },
  { value: "Research Coordinator", label: "Research Coordinator" },
  { value: "Study Monitor", label: "Study Monitor" },
  { value: "Data Manager", label: "Data Manager" },
  { value: "Other", label: "Other" },
];

export const yearOptionsForPrevPlus10Years = [
  { value: "", label: "Select year" },
  ...Array.from({ length: 12 }, (_, i) => {
    const year = currentYear - 1 + i;
    return { value: year.toString(), label: year.toString() };
  }),
];
 
export const yearOptionsFom1950Plus10Years = [
  { value: "", label: "Select year" },
  ...Array.from(
    { length: currentYear + 10 - 1950 + 1 },
    (_, i) => {
      const year = 1950 + i;
      return { value: year.toString(), label: year.toString() };
    }
  ),
];
